Stay Sphere Hotel Rails and Ruby Final Capstone  👨‍💻 👨‍💻 👨‍💻
tsheporamantso/final-capstone-rails-api pull request #20
Opened 2024-03-06 10:19 UTC by tsheporamantso

## Stay Sphere Hotel Rails and Ruby Final Capstone  👨‍💻 👨‍💻 👨‍💻 
### On this milestone 🗿  we managed to implement the following
- [ ] We are a team of 3 i.e. 
     - @evansnyamekye 
     - @George7h 
     - @tsheporamantso 
- [ ] [Link](https://github.com/tsheporamantso/final-capstone-react-front-end) to Front-End Applications
1. The user logs in to the website, only by typing the username (a proper authenticated login is a requirement if your group is made of 5 people).
2. In the navigation panel, the user can see links to:
   - Motorcycles/doctors/classes/items that you selected as a theme.
   - "Reserve" form.
   - "My reservations".
   - "Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
   - "Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
3. On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).

4. When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).

   - In the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).

5. When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.

6. Make the app responsive, creating both mobile and desktop versions.

##### Additional features - Required for teams with 3-4 & 5 members (optional for others)

7. When the user clicks the "Delete item" link in the navigation panel they can see a list of all items with title and "Delete" button.
   - When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.

- To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
  - Use the design based on the ["Book a vespa test-ride"](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583) and add all necessary inputs.
  - The user can also access the "Reserve" page from the navigation panel. In that case only username is autofilled.

8. When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).
9. Add full documentation for your API.
10. Check and Correct Stylelint errors
11. Followed correct Gitflow

2024-03-06 17:07 UTC, vichuge reviewed
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

### Front-end CR [here](https://github.com/tsheporamantso/final-capstone-react-front-end/pull/21#pullrequestreview-1920339556)

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-03-06 17:07 UTC, vichuge commented on config/routes.rb
> +        resources :reservations
- A good practice for routes, and more when not all resources are used, is to use the statement `only:`. This help to open only the used routes in the controller.

2024-03-06 17:07 UTC, vichuge commented on spec/integration/api_spec.rb
> +require 'swagger_helper'
- It looks like there are some tests to fix here, I kindly invite you to do it.

```
rspec ./spec/integration/api_spec.rb:21 # Places API /api/v1/places post place created returns a 201 response
rspec ./spec/integration/api_spec.rb:26 # Places API /api/v1/places post invalid request returns a 422 response
rspec ./spec/integration/api_spec.rb:39 # Places API /api/v1/places/{id} get place found returns a 200 response
rspec ./spec/integration/api_spec.rb:81 # Places API /api/v1/places/{id} put place updated returns a 200 response
rspec ./spec/integration/api_spec.rb:87 # Places API /api/v1/places/{id} put invalid request returns a 422 response
rspec ./spec/integration/api_spec.rb:101 # Places API /api/v1/places/{id} delete place deleted returns a 200 response
rspec ./spec/integration/api_spec.rb:118 # Places API /api/v1/places get places found returns a 200 response
rspec ./spec/integration/api_spec.rb:147 # Reservations API /api/v1/users/{user_id}/reservations get reservations found returns a 200 response
rspec ./spec/integration/api_spec.rb:173 # Reservations API /api/v1/users/{user_id}/reservations/{id} get reservation found returns a 200 response
rspec ./spec/integration/api_spec.rb:213 # Reservations API /api/v1/users/{user_id}/reservations post reservation created returns a 201 response
rspec ./spec/integration/api_spec.rb:219 # Reservations API /api/v1/users/{user_id}/reservations post invalid request returns a 422 response
rspec ./spec/integration/api_spec.rb:244 # Reservations API /api/v1/users/{user_id}/reservations/{id} put reservation updated returns a 200 response
rspec ./spec/integration/api_spec.rb:251 # Reservations API /api/v1/users/{user_id}/reservations/{id} put invalid request returns a 422 response
rspec ./spec/integration/api_spec.rb:266 # Reservations API /api/v1/users/{user_id}/reservations/{id} /api/v1/users/{user_id}/reservations/{id} delete reservation deleted returns a 204 response
```

2024-03-06 17:07 UTC, vichuge commented on db/seeds.rb
> +User.create!(
Thanks for add seeds to the project :)

2024-03-06 20:04 UTC, tsheporamantso commented on db/seeds.rb
> +User.create!(
<img src="https://media3.giphy.com/media/FmBhzktIjvdZe/giphy.gif"/>
You are most welcome. 🤝

2024-03-06 20:04 UTC, tsheporamantso commented on spec/integration/api_spec.rb
> +require 'swagger_helper'
Thank you very much for the review. However, I would appreciate your guidance in this regard. I ran the following command `rake rswag:specs:swaggerize` to check API documentation test cases and all 18 tests passed. please see screenshot
![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/110445380/1f15f675-820e-4b4c-ac3c-bb3d97f66c60)
To further test for validations I used the following command `rspec ./spec/models/user_spec.rb` and my test cases passed as well 
![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/110445380/8c8394c0-89e6-478b-8d93-6ab73118b098)

2024-03-06 20:04 UTC, tsheporamantso commented on config/routes.rb
> +        resources :reservations
Thank you very much for your insightful review and recommendation will do as recommended.

2024-03-07 09:11 UTC, tsheporamantso commented
Good day Reviewer
Please see the below screenshot as proof that API has been documented accordingly.

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/110445380/1c72ccf3-cd77-4b19-a9f3-129812cc4fb5)

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/110445380/90caabcc-1f6e-48a6-84d3-d319ed84b5c3)

2024-03-07 11:21 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Routes have been improved✔️
-  Nice code organization ✔️ 
-  API is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-03-07 11:21 UTC, Meltrust commented on README.md
> +
- [x]  In order to prevent your users from getting failing tests like in the previous review, and make them all pass with 2 commands, kindly add these instructions to your readme in the "test" section:

### Please input these commands in order to run the tests:

```bash
rspec spec/models
rake rswag
```

Result for your users:

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/57421823/9c631155-2242-4413-800a-0ccae5ad4ade)

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/57421823/609c94f1-e931-4ffa-be54-4cfef0861a22)

That way, the documentation for running the tests will be precise, and no user will get failing/wrong tests. 👍

2024-03-07 11:24 UTC, tsheporamantso commented on README.md
> +
Thank you very much @Meltrust 
<img src="https://media2.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif"/>

2024-03-07 11:53 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Readme test instructions are now specific✔️ 
- Place model association now removes its reservations upon deletion ✔️ 
- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2024-03-07 12:15 UTC, merged